import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// let obj={name:'',age:''}
// obj.name
// const {name}=obj

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-400 p-5 flex gap-5">
          <Link href="/">Home</Link>
          <Link href="/dashboard">Dashboard</Link>
          <Link href="/dashboard/customers">Customer</Link>
          <Link href="/settings">Settings</Link>
          <Link href="/team">Team</Link>
          <Link href="/teamDetail">Team Detail</Link>
          <Link href="/blog">Blog</Link>
        </header>
        {children}
        <footer className="bg-slate-300 p-5">This is footer</footer>
      </body>
    </html>
  );
}
